# Generated by Django 5.0.6 on 2024-05-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
