# Generated by Django 5.0.3 on 2024-05-31 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_poll_category_alter_poll_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='poll.poll'),
        ),
    ]
