# Generated by Django 5.0.6 on 2024-05-22 16:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='options',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='user_id',
        ),
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(default=datetime.datetime(2024, 5, 22, 16, 9, 53, 420371, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='option',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='total_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
